Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: organizations/ordererOrganizations/lgsvhr.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &HROrg
    Name: HRMSP
    ID: HRMSP
    MSPDir: organizations/peerOrganizations/hr.lgsvhr.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('HRMSP.admin', 'HRMSP.peer', 'HRMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('HRMSP.admin', 'HRMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('HRMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('HRMSP.peer')"
    AnchorPeers:
      - Host: peer0.hr.lgsvhr.com
        Port: 7051

  - &PayrollOrg
    Name: PayrollMSP
    ID: PayrollMSP
    MSPDir: organizations/peerOrganizations/payroll.lgsvhr.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('PayrollMSP.admin', 'PayrollMSP.peer', 'PayrollMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('PayrollMSP.admin', 'PayrollMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('PayrollMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('PayrollMSP.peer')"
    AnchorPeers:
      - Host: peer0.payroll.lgsvhr.com
        Port: 7051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.lgsvhr.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.lgsvhr.com
        Port: 7050
        ClientTLSCert: organizations/ordererOrganizations/lgsvhr.com/orderers/orderer.lgsvhr.com/tls/server.crt
        ServerTLSCert: organizations/ordererOrganizations/lgsvhr.com/orderers/orderer.lgsvhr.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  LGSVHRGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      LGSVHRConsortium:
        Organizations:
          - *HROrg
          - *PayrollOrg

  LGSVHRPayrollChannel:
    Consortium: LGSVHRConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *HROrg
        - *PayrollOrg
