OrdererOrgs:
  - Name: Orderer
    Domain: lgsvhr.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
          - orderer.lgsvhr.com

PeerOrgs:
  - Name: HR
    Domain: hr.lgsvhr.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1

  - Name: Payroll
    Domain: payroll.lgsvhr.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1
