UPDATE MFA_CHALLENGE
   SET Status = 'EXPIRED'
 WHERE Status = 'PENDING';

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MFA_CHALLENGE' AND INDEX_NAME = 'idx_mfa_challenge_phone_hash') > 0, 'DROP INDEX idx_mfa_challenge_phone_hash ON MFA_CHALLENGE', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MFA_CHALLENGE' AND COLUMN_NAME = 'Phone_Number_Hash') > 0, 'ALTER TABLE MFA_CHALLENGE DROP COLUMN Phone_Number_Hash', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MFA_CHALLENGE' AND COLUMN_NAME = 'Phone_Number_Encrypted') > 0, 'ALTER TABLE MFA_CHALLENGE DROP COLUMN Phone_Number_Encrypted', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
