CREATE TABLE IF NOT EXISTS MFA_CHALLENGE (
  Challenge_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  Employee_ID BIGINT NOT NULL,
  Provider VARCHAR(50) NOT NULL DEFAULT 'iprog',
  Phone_Number VARCHAR(20) NULL,
  Phone_Number_Encrypted TEXT NULL,
  Phone_Number_Hash CHAR(64) NULL,
  Challenge_Token_Hash CHAR(64) NOT NULL,
  Status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  Attempt_Count INT NOT NULL DEFAULT 0,
  Resend_Count INT NOT NULL DEFAULT 0,
  Last_Sent_At DATETIME NULL,
  Expires_At DATETIME NOT NULL,
  Verified_At DATETIME NULL,
  Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_At DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_mfa_challenge_employee_status (Employee_ID, Status),
  INDEX idx_mfa_challenge_expires (Expires_At),
  INDEX idx_mfa_challenge_phone_hash (Phone_Number_Hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MFA_CHALLENGE' AND COLUMN_NAME = 'Phone_Number') = 0, 'ALTER TABLE MFA_CHALLENGE ADD COLUMN Phone_Number VARCHAR(20) NULL AFTER Provider', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MFA_CHALLENGE' AND COLUMN_NAME = 'Phone_Number_Encrypted') = 0, 'ALTER TABLE MFA_CHALLENGE ADD COLUMN Phone_Number_Encrypted TEXT NULL AFTER Phone_Number', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MFA_CHALLENGE' AND COLUMN_NAME = 'Phone_Number_Hash') = 0, 'ALTER TABLE MFA_CHALLENGE ADD COLUMN Phone_Number_Hash CHAR(64) NULL AFTER Phone_Number_Encrypted', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MFA_CHALLENGE' AND INDEX_NAME = 'idx_mfa_challenge_phone_hash') = 0, 'CREATE INDEX idx_mfa_challenge_phone_hash ON MFA_CHALLENGE (Phone_Number_Hash)', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

UPDATE MFA_CHALLENGE
   SET Phone_Number_Hash = SHA2(Phone_Number, 256)
 WHERE Phone_Number IS NOT NULL
   AND Phone_Number <> ''
   AND Phone_Number_Hash IS NULL;
