ALTER TABLE employee_offboarding_case
  DROP COLUMN processed_by,
  DROP COLUMN it_processed_at,
  DROP COLUMN it_processed_by,
  DROP COLUMN biometric_access_removed,
  DROP COLUMN sessions_invalidated,
  DROP COLUMN permissions_revoked,
  DROP COLUMN it_access_status,
  DROP COLUMN final_pay_remarks,
  DROP COLUMN final_pay_release_date,
  DROP COLUMN final_pay_approved_at,
  DROP COLUMN final_pay_approved_by,
  DROP COLUMN payroll_remarks,
  DROP COLUMN benefits_or_13th_month_checked,
  DROP COLUMN loans_or_cash_advances_checked,
  DROP COLUMN deductions_checked,
  DROP COLUMN leave_balance_checked,
  DROP COLUMN attendance_checked,
  DROP COLUMN last_payroll_period_checked,
  DROP COLUMN payroll_checked_at,
  DROP COLUMN payroll_checked_by,
  DROP COLUMN payroll_clearance_status,
  DROP COLUMN attendance_leave_clearance,
  DROP COLUMN exit_interview_status,
  DROP COLUMN turnover_status,
  DROP COLUMN company_property_status,
  MODIFY COLUMN final_pay_status ENUM('Pending','For Processing','Processed','Released') NOT NULL DEFAULT 'Pending',
  MODIFY COLUMN status ENUM('Pending','Approved','Completed','Cancelled') NOT NULL DEFAULT 'Pending';
