ALTER TABLE module_rollback_requests
  DROP CONSTRAINT chk_module_rollback_completed_evidence,
  DROP CONSTRAINT chk_module_rollback_approval_evidence,
  DROP CONSTRAINT chk_module_rollback_idempotency,
  DROP CONSTRAINT chk_module_rollback_versions,
  DROP CONSTRAINT chk_module_rollback_maker_checker,
  DROP FOREIGN KEY fk_module_rollback_step_up,
  DROP FOREIGN KEY fk_module_rollback_updated_by,
  DROP FOREIGN KEY fk_module_rollback_rejected_by,
  DROP FOREIGN KEY fk_module_rollback_approved_by,
  DROP FOREIGN KEY fk_module_rollback_requested_by,
  DROP FOREIGN KEY fk_module_rollback_recovery,
  DROP INDEX idx_module_rollback_updated_by,
  DROP INDEX idx_module_rollback_rejected_by,
  DROP INDEX idx_module_rollback_approved_by,
  DROP INDEX idx_module_rollback_step_up,
  DROP INDEX idx_module_rollback_lease,
  DROP INDEX idx_module_rollback_integrity,
  DROP INDEX idx_module_rollback_approval,
  DROP INDEX idx_module_rollback_recovery,
  DROP INDEX uq_module_rollback_idempotency;

ALTER TABLE module_rollback_requests
  DROP COLUMN IF EXISTS updated_by,
  DROP COLUMN IF EXISTS worker_lease_expires_at,
  DROP COLUMN IF EXISTS worker_lease_token_hash,
  DROP COLUMN IF EXISTS attempt_count,
  DROP COLUMN IF EXISTS failure_message_encrypted,
  DROP COLUMN IF EXISTS cancelled_at,
  DROP COLUMN IF EXISTS failed_at,
  DROP COLUMN IF EXISTS updated_at,
  DROP COLUMN IF EXISTS started_at,
  DROP COLUMN IF EXISTS integrity_report_encrypted,
  DROP COLUMN IF EXISTS integrity_checked_at,
  DROP COLUMN IF EXISTS integrity_status,
  DROP COLUMN IF EXISTS verification_status,
  DROP COLUMN IF EXISTS checksum_algorithm,
  DROP COLUMN IF EXISTS artifact_checksum,
  DROP COLUMN IF EXISTS step_up_verified_at,
  DROP COLUMN IF EXISTS step_up_challenge_id,
  DROP COLUMN IF EXISTS approval_notes_encrypted,
  DROP COLUMN IF EXISTS rejected_at,
  DROP COLUMN IF EXISTS rejected_by,
  DROP COLUMN IF EXISTS approved_at,
  DROP COLUMN IF EXISTS approval_status,
  DROP COLUMN IF EXISTS recovery_point_id,
  DROP COLUMN IF EXISTS idempotency_key,
  MODIFY COLUMN status ENUM('PENDING','APPROVED','IN_PROGRESS','COMPLETED','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  MODIFY COLUMN requested_by BIGINT NOT NULL,
  MODIFY COLUMN approved_by BIGINT NULL;

ALTER TABLE restore_jobs
  DROP CONSTRAINT chk_restore_jobs_completed_evidence,
  DROP CONSTRAINT chk_restore_jobs_approval_evidence,
  DROP CONSTRAINT chk_restore_jobs_idempotency,
  DROP CONSTRAINT chk_restore_jobs_maker_checker,
  DROP FOREIGN KEY fk_restore_jobs_step_up,
  DROP FOREIGN KEY fk_restore_jobs_updated_by,
  DROP FOREIGN KEY fk_restore_jobs_rejected_by,
  DROP FOREIGN KEY fk_restore_jobs_approved_by,
  DROP FOREIGN KEY fk_restore_jobs_requested_by,
  DROP FOREIGN KEY fk_restore_jobs_backup_set,
  DROP INDEX idx_restore_jobs_updated_by,
  DROP INDEX idx_restore_jobs_rejected_by,
  DROP INDEX idx_restore_jobs_approved_by,
  DROP INDEX idx_restore_jobs_requested_by,
  DROP INDEX idx_restore_jobs_step_up,
  DROP INDEX idx_restore_jobs_lease,
  DROP INDEX idx_restore_jobs_integrity,
  DROP INDEX idx_restore_jobs_dry_run,
  DROP INDEX idx_restore_jobs_approval,
  DROP INDEX uq_restore_jobs_idempotency;

ALTER TABLE restore_jobs
  DROP COLUMN IF EXISTS updated_by,
  DROP COLUMN IF EXISTS worker_lease_expires_at,
  DROP COLUMN IF EXISTS worker_lease_token_hash,
  DROP COLUMN IF EXISTS attempt_count,
  DROP COLUMN IF EXISTS failure_message_encrypted,
  DROP COLUMN IF EXISTS cancelled_at,
  DROP COLUMN IF EXISTS failed_at,
  DROP COLUMN IF EXISTS restore_target_encrypted,
  DROP COLUMN IF EXISTS restored_checksum,
  DROP COLUMN IF EXISTS expected_checksum,
  DROP COLUMN IF EXISTS integrity_report_encrypted,
  DROP COLUMN IF EXISTS integrity_checked_at,
  DROP COLUMN IF EXISTS integrity_status,
  DROP COLUMN IF EXISTS dry_run_result_encrypted,
  DROP COLUMN IF EXISTS dry_run_target_encrypted,
  DROP COLUMN IF EXISTS dry_run_completed_at,
  DROP COLUMN IF EXISTS dry_run_started_at,
  DROP COLUMN IF EXISTS dry_run_status,
  DROP COLUMN IF EXISTS step_up_verified_at,
  DROP COLUMN IF EXISTS step_up_challenge_id,
  DROP COLUMN IF EXISTS approval_notes_encrypted,
  DROP COLUMN IF EXISTS rejected_at,
  DROP COLUMN IF EXISTS rejected_by,
  DROP COLUMN IF EXISTS approved_at,
  DROP COLUMN IF EXISTS approval_status,
  DROP COLUMN IF EXISTS idempotency_key,
  MODIFY COLUMN status ENUM('PENDING','IN_PROGRESS','COMPLETED','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  MODIFY COLUMN requested_by BIGINT NOT NULL,
  MODIFY COLUMN approved_by BIGINT NULL;

ALTER TABLE module_recovery_points
  DROP CONSTRAINT chk_module_recovery_available_evidence,
  DROP CONSTRAINT chk_module_recovery_identifiers,
  DROP CONSTRAINT chk_module_recovery_artifact_size,
  DROP FOREIGN KEY fk_module_recovery_updated_by,
  DROP FOREIGN KEY fk_module_recovery_created_by,
  DROP FOREIGN KEY fk_module_recovery_backup_set,
  DROP INDEX idx_module_recovery_updated_by,
  DROP INDEX idx_module_recovery_created_by,
  DROP INDEX idx_module_recovery_integrity,
  DROP INDEX idx_module_recovery_status,
  DROP INDEX uq_module_recovery_reference,
  DROP INDEX uq_module_recovery_idempotency;

ALTER TABLE module_recovery_points
  DROP COLUMN IF EXISTS updated_at,
  DROP COLUMN IF EXISTS updated_by,
  DROP COLUMN IF EXISTS expires_at,
  DROP COLUMN IF EXISTS verified_at,
  DROP COLUMN IF EXISTS integrity_status,
  DROP COLUMN IF EXISTS verification_status,
  DROP COLUMN IF EXISTS artifact_size_bytes,
  DROP COLUMN IF EXISTS checksum_algorithm,
  DROP COLUMN IF EXISTS artifact_checksum,
  DROP COLUMN IF EXISTS status,
  DROP COLUMN IF EXISTS recovery_reference,
  DROP COLUMN IF EXISTS idempotency_key,
  MODIFY COLUMN created_by BIGINT NOT NULL;

ALTER TABLE backup_sets
  DROP CONSTRAINT chk_backup_sets_verified_artifact,
  DROP CONSTRAINT chk_backup_sets_artifact_size,
  DROP CONSTRAINT chk_backup_sets_idempotency,
  DROP CONSTRAINT chk_backup_sets_maker_checker,
  DROP FOREIGN KEY fk_backup_sets_step_up,
  DROP FOREIGN KEY fk_backup_sets_verified_by,
  DROP FOREIGN KEY fk_backup_sets_rejected_by,
  DROP FOREIGN KEY fk_backup_sets_approved_by,
  DROP FOREIGN KEY fk_backup_sets_updated_by,
  DROP FOREIGN KEY fk_backup_sets_created_by,
  DROP INDEX idx_backup_sets_verified_by,
  DROP INDEX idx_backup_sets_rejected_by,
  DROP INDEX idx_backup_sets_approved_by,
  DROP INDEX idx_backup_sets_updated_by,
  DROP INDEX idx_backup_sets_step_up,
  DROP INDEX idx_backup_sets_lease,
  DROP INDEX idx_backup_sets_approval,
  DROP INDEX uq_backup_sets_idempotency;

ALTER TABLE backup_sets
  DROP COLUMN IF EXISTS updated_by,
  DROP COLUMN IF EXISTS worker_lease_expires_at,
  DROP COLUMN IF EXISTS worker_lease_token_hash,
  DROP COLUMN IF EXISTS attempt_count,
  DROP COLUMN IF EXISTS failure_message_encrypted,
  DROP COLUMN IF EXISTS cancelled_at,
  DROP COLUMN IF EXISTS failed_at,
  DROP COLUMN IF EXISTS completed_at,
  DROP COLUMN IF EXISTS started_at,
  DROP COLUMN IF EXISTS adapter_metadata_encrypted,
  DROP COLUMN IF EXISTS verified_by,
  DROP COLUMN IF EXISTS integrity_status,
  DROP COLUMN IF EXISTS verification_status,
  DROP COLUMN IF EXISTS verified_checksum,
  DROP COLUMN IF EXISTS checksum_algorithm,
  DROP COLUMN IF EXISTS artifact_format,
  DROP COLUMN IF EXISTS step_up_verified_at,
  DROP COLUMN IF EXISTS step_up_challenge_id,
  DROP COLUMN IF EXISTS rejected_at,
  DROP COLUMN IF EXISTS rejected_by,
  DROP COLUMN IF EXISTS approved_at,
  DROP COLUMN IF EXISTS approved_by,
  DROP COLUMN IF EXISTS approval_status,
  DROP COLUMN IF EXISTS idempotency_key,
  MODIFY COLUMN status ENUM('PENDING','RUNNING','COMPLETED','FAILED','VERIFIED','RESTORED') NOT NULL DEFAULT 'PENDING',
  MODIFY COLUMN created_by BIGINT NOT NULL;

DROP TABLE IF EXISTS backup_step_up_challenges;
