CREATE TABLE IF NOT EXISTS payroll_attendance_configurations (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  config_name VARCHAR(120) NOT NULL,
  scope_type ENUM('DEFAULT','DEPARTMENT','EMPLOYMENT_TYPE','WAGE_TYPE','EMPLOYEE') NOT NULL DEFAULT 'DEFAULT',
  employee_id BIGINT NULL,
  department_id BIGINT NULL,
  wage_type_id BIGINT NULL,
  scope_value VARCHAR(120) NULL,
  work_start_time TIME NULL,
  work_end_time TIME NULL,
  break_start_time TIME NULL,
  break_end_time TIME NULL,
  daily_hours DECIMAL(5,2) NULL,
  standard_work_hours DECIMAL(5,2) NULL,
  working_days_per_month DECIMAL(6,2) NULL,
  working_days_per_year INT NULL,
  grace_period_minutes INT NOT NULL DEFAULT 0,
  late_threshold_minutes INT NOT NULL DEFAULT 0,
  habitual_tardiness_threshold INT NOT NULL DEFAULT 5,
  habitual_tardiness_period ENUM('MONTHLY','PAYROLL_PERIOD') NOT NULL DEFAULT 'MONTHLY',
  tardiness_alert_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  priority INT NOT NULL DEFAULT 0,
  effective_date DATE NOT NULL,
  end_date DATE NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  notes TEXT NULL,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_payroll_att_config_scope (scope_type, employee_id, department_id, wage_type_id, scope_value, is_active),
  INDEX idx_payroll_att_config_effective (effective_date, end_date, is_active),
  INDEX idx_payroll_att_config_priority (priority, effective_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
