-- UP migration: permissioned blockchain payroll audit layer
-- LGSV HR stores operational payroll data in MySQL and records only finalized
-- payroll hashes plus audit metadata on Hyperledger Fabric.

CREATE TABLE IF NOT EXISTS PAYROLL_RECORD (
  Payroll_ID BIGINT PRIMARY KEY,
  Employee_ID BIGINT NOT NULL,
  Gross_Pay DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  Total_Statutory_Deductions DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  Net_Pay DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  Non_Taxable_Allowance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  Approval_Status VARCHAR(50) NOT NULL DEFAULT 'Draft',
  Transaction_Hash VARCHAR(255) NULL,
  Blockchain_Status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  Finalized_At DATETIME NULL,
  Approved_By BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET @sql = IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PAYROLL_RECORD' AND COLUMN_NAME = 'Transaction_Hash') = 0,
  'ALTER TABLE PAYROLL_RECORD ADD COLUMN Transaction_Hash VARCHAR(255) NULL',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PAYROLL_RECORD' AND COLUMN_NAME = 'Blockchain_Status') = 0,
  'ALTER TABLE PAYROLL_RECORD ADD COLUMN Blockchain_Status VARCHAR(50) NOT NULL DEFAULT ''PENDING''',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PAYROLL_RECORD' AND COLUMN_NAME = 'Finalized_At') = 0,
  'ALTER TABLE PAYROLL_RECORD ADD COLUMN Finalized_At DATETIME NULL',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PAYROLL_RECORD' AND COLUMN_NAME = 'Approved_By') = 0,
  'ALTER TABLE PAYROLL_RECORD ADD COLUMN Approved_By BIGINT NULL',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PAYROLL_RECORD' AND INDEX_NAME = 'idx_payroll_record_employee') = 0,
  'CREATE INDEX idx_payroll_record_employee ON PAYROLL_RECORD (Employee_ID)',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PAYROLL_RECORD' AND INDEX_NAME = 'idx_payroll_record_status') = 0,
  'CREATE INDEX idx_payroll_record_status ON PAYROLL_RECORD (Approval_Status, Blockchain_Status)',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PAYROLL_RECORD' AND INDEX_NAME = 'idx_payroll_record_hash') = 0,
  'CREATE INDEX idx_payroll_record_hash ON PAYROLL_RECORD (Transaction_Hash)',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS system_audit_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  employee_id BIGINT NULL,
  target_employee_id BIGINT NULL,
  action_performed TEXT NOT NULL,
  module VARCHAR(80) NULL,
  old_value TEXT NULL,
  new_value TEXT NULL,
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(500) NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  Action_Type VARCHAR(100) NOT NULL DEFAULT 'SYSTEM_EVENT',
  Description TEXT NULL,
  Created_At DATETIME NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'user_id') = 0, 'ALTER TABLE system_audit_log ADD COLUMN user_id INT NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'employee_id') = 0, 'ALTER TABLE system_audit_log ADD COLUMN employee_id BIGINT NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'target_employee_id') = 0, 'ALTER TABLE system_audit_log ADD COLUMN target_employee_id BIGINT NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'action_performed') = 0, 'ALTER TABLE system_audit_log ADD COLUMN action_performed TEXT NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'Action_Type') = 0, 'ALTER TABLE system_audit_log ADD COLUMN Action_Type VARCHAR(100) NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

UPDATE system_audit_log
   SET action_performed = COALESCE(NULLIF(action_performed, ''), COALESCE(Action_Type, 'SYSTEM_EVENT'))
 WHERE action_performed IS NULL OR action_performed = '';

ALTER TABLE system_audit_log
  MODIFY COLUMN action_performed TEXT NOT NULL;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'module') = 0, 'ALTER TABLE system_audit_log ADD COLUMN module VARCHAR(80) NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'old_value') = 0, 'ALTER TABLE system_audit_log ADD COLUMN old_value TEXT NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'new_value') = 0, 'ALTER TABLE system_audit_log ADD COLUMN new_value TEXT NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'ip_address') = 0, 'ALTER TABLE system_audit_log ADD COLUMN ip_address VARCHAR(45) NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'user_agent') = 0, 'ALTER TABLE system_audit_log ADD COLUMN user_agent VARCHAR(500) NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'timestamp') = 0, 'ALTER TABLE system_audit_log ADD COLUMN timestamp DATETIME DEFAULT CURRENT_TIMESTAMP', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

UPDATE system_audit_log
   SET Action_Type = COALESCE(NULLIF(Action_Type, ''), 'SYSTEM_EVENT')
 WHERE Action_Type IS NULL OR Action_Type = '';

ALTER TABLE system_audit_log
  MODIFY COLUMN Action_Type VARCHAR(100) NOT NULL DEFAULT 'SYSTEM_EVENT';

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'Description') = 0, 'ALTER TABLE system_audit_log ADD COLUMN Description TEXT NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND COLUMN_NAME = 'Created_At') = 0, 'ALTER TABLE system_audit_log ADD COLUMN Created_At DATETIME NULL DEFAULT CURRENT_TIMESTAMP', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND INDEX_NAME = 'idx_system_audit_employee') = 0, 'CREATE INDEX idx_system_audit_employee ON system_audit_log (employee_id)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND INDEX_NAME = 'idx_system_audit_module_time') = 0, 'CREATE INDEX idx_system_audit_module_time ON system_audit_log (module, timestamp)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'system_audit_log' AND INDEX_NAME = 'idx_system_audit_action_type') = 0, 'CREATE INDEX idx_system_audit_action_type ON system_audit_log (Action_Type)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS BLOCKCHAIN_AUDIT_LOG (
  Audit_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  Payroll_ID BIGINT NOT NULL,
  Event_Type VARCHAR(80) NOT NULL,
  Actor_User_ID BIGINT NULL,
  Actor_Role VARCHAR(80) NULL,
  Transaction_Hash VARCHAR(255) NULL,
  Payload_Hash CHAR(64) NULL,
  Status VARCHAR(50) NOT NULL,
  IP_Address VARCHAR(45) NULL,
  Details JSON NULL,
  Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_blockchain_audit_payroll (Payroll_ID),
  INDEX idx_blockchain_audit_status (Status, Created_At),
  INDEX idx_blockchain_audit_hash (Payload_Hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
