ALTER TABLE payroll_piece_rates
  MODIFY COLUMN IF EXISTS piece_rate DECIMAL(12,4) NOT NULL DEFAULT 0.0000;

ALTER TABLE payroll_production_outputs
  MODIFY COLUMN IF EXISTS piece_rate DECIMAL(12,4) NOT NULL DEFAULT 0.0000;

ALTER TABLE payroll_production_pairs
  MODIFY COLUMN IF EXISTS piece_rate DECIMAL(12,4) NOT NULL DEFAULT 0.0000;

ALTER TABLE piece_rate_outputs
  MODIFY COLUMN IF EXISTS rate_per_piece DECIMAL(12,4) NOT NULL DEFAULT 0.0000;
