ALTER TABLE employee_offboarding_case
  DROP COLUMN IF EXISTS processed_by,
  DROP COLUMN IF EXISTS it_processed_at,
  DROP COLUMN IF EXISTS it_processed_by,
  DROP COLUMN IF EXISTS biometric_access_removed,
  DROP COLUMN IF EXISTS sessions_invalidated,
  DROP COLUMN IF EXISTS permissions_revoked,
  DROP COLUMN IF EXISTS it_access_status,
  DROP COLUMN IF EXISTS final_pay_remarks,
  DROP COLUMN IF EXISTS final_pay_release_date,
  DROP COLUMN IF EXISTS final_pay_approved_at,
  DROP COLUMN IF EXISTS final_pay_approved_by,
  DROP COLUMN IF EXISTS payroll_remarks,
  DROP COLUMN IF EXISTS benefits_or_13th_month_checked,
  DROP COLUMN IF EXISTS loans_or_cash_advances_checked,
  DROP COLUMN IF EXISTS deductions_checked,
  DROP COLUMN IF EXISTS leave_balance_checked,
  DROP COLUMN IF EXISTS attendance_checked,
  DROP COLUMN IF EXISTS last_payroll_period_checked,
  DROP COLUMN IF EXISTS payroll_checked_at,
  DROP COLUMN IF EXISTS payroll_checked_by,
  DROP COLUMN IF EXISTS payroll_clearance_status,
  DROP COLUMN IF EXISTS attendance_leave_clearance,
  DROP COLUMN IF EXISTS exit_interview_status,
  DROP COLUMN IF EXISTS turnover_status,
  DROP COLUMN IF EXISTS company_property_status,
  MODIFY COLUMN final_pay_status ENUM('Pending','For Processing','Processed','Released') NOT NULL DEFAULT 'Pending',
  MODIFY COLUMN status ENUM('Pending','Approved','Completed','Cancelled') NOT NULL DEFAULT 'Pending';
