-- Switch privileged-role MFA from paid SMS OTP to authenticator-app TOTP.
UPDATE MFA_CHALLENGE
   SET Status = 'SUPERSEDED'
 WHERE Status = 'PENDING';

SET @sql = IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'employees' AND COLUMN_NAME = 'MFA_TOTP_Secret_Encrypted') = 0,
  'ALTER TABLE employees ADD COLUMN MFA_TOTP_Secret_Encrypted TEXT NULL',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'employees' AND COLUMN_NAME = 'MFA_TOTP_Secret_Hash') = 0,
  'ALTER TABLE employees ADD COLUMN MFA_TOTP_Secret_Hash CHAR(64) NULL',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'employees' AND COLUMN_NAME = 'MFA_TOTP_Enrolled_At') = 0,
  'ALTER TABLE employees ADD COLUMN MFA_TOTP_Enrolled_At DATETIME NULL',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'employees' AND INDEX_NAME = 'idx_employees_mfa_totp_hash') = 0,
  'CREATE INDEX idx_employees_mfa_totp_hash ON employees (MFA_TOTP_Secret_Hash)',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

ALTER TABLE MFA_CHALLENGE
  MODIFY COLUMN Provider VARCHAR(50) NOT NULL DEFAULT 'totp';
