ALTER TABLE employee_offboarding_case
  MODIFY COLUMN status ENUM('Pending','In Progress','Approved','Completed','Cancelled') NOT NULL DEFAULT 'Pending',
  MODIFY COLUMN final_pay_status ENUM('Pending','For Processing','For Approval','Approved','Processed','Released','With Issue') NOT NULL DEFAULT 'Pending',
  ADD COLUMN IF NOT EXISTS company_property_status ENUM('Pending','Partially Returned','Completed','Not Applicable') NOT NULL DEFAULT 'Pending' AFTER clearance_status,
  ADD COLUMN IF NOT EXISTS turnover_status ENUM('Pending','Completed','Not Required') NOT NULL DEFAULT 'Pending' AFTER company_property_status,
  ADD COLUMN IF NOT EXISTS exit_interview_status ENUM('Pending','Completed','Not Required') NOT NULL DEFAULT 'Pending' AFTER turnover_status,
  ADD COLUMN IF NOT EXISTS attendance_leave_clearance ENUM('Pending','Checked','With Issue') NOT NULL DEFAULT 'Pending' AFTER exit_interview_status,
  ADD COLUMN IF NOT EXISTS payroll_clearance_status ENUM('Pending','Checked','Cleared','With Issue') NOT NULL DEFAULT 'Pending' AFTER attendance_leave_clearance,
  ADD COLUMN IF NOT EXISTS payroll_checked_by INT NULL AFTER payroll_clearance_status,
  ADD COLUMN IF NOT EXISTS payroll_checked_at DATETIME NULL AFTER payroll_checked_by,
  ADD COLUMN IF NOT EXISTS last_payroll_period_checked ENUM('Yes','No') NOT NULL DEFAULT 'No' AFTER payroll_checked_at,
  ADD COLUMN IF NOT EXISTS attendance_checked ENUM('Yes','No') NOT NULL DEFAULT 'No' AFTER last_payroll_period_checked,
  ADD COLUMN IF NOT EXISTS leave_balance_checked ENUM('Yes','No') NOT NULL DEFAULT 'No' AFTER attendance_checked,
  ADD COLUMN IF NOT EXISTS deductions_checked ENUM('Yes','No') NOT NULL DEFAULT 'No' AFTER leave_balance_checked,
  ADD COLUMN IF NOT EXISTS loans_or_cash_advances_checked ENUM('Yes','No','Not Applicable') NOT NULL DEFAULT 'No' AFTER deductions_checked,
  ADD COLUMN IF NOT EXISTS benefits_or_13th_month_checked ENUM('Yes','No') NOT NULL DEFAULT 'No' AFTER loans_or_cash_advances_checked,
  ADD COLUMN IF NOT EXISTS payroll_remarks VARCHAR(500) NULL AFTER benefits_or_13th_month_checked,
  ADD COLUMN IF NOT EXISTS final_pay_approved_by INT NULL AFTER final_pay_status,
  ADD COLUMN IF NOT EXISTS final_pay_approved_at DATETIME NULL AFTER final_pay_approved_by,
  ADD COLUMN IF NOT EXISTS final_pay_release_date DATE NULL AFTER final_pay_approved_at,
  ADD COLUMN IF NOT EXISTS final_pay_remarks VARCHAR(500) NULL AFTER final_pay_release_date,
  ADD COLUMN IF NOT EXISTS it_access_status ENUM('Pending','Disabled','Revoked') NOT NULL DEFAULT 'Pending' AFTER final_pay_remarks,
  ADD COLUMN IF NOT EXISTS permissions_revoked TINYINT(1) NOT NULL DEFAULT 0 AFTER it_access_status,
  ADD COLUMN IF NOT EXISTS sessions_invalidated TINYINT(1) NOT NULL DEFAULT 0 AFTER permissions_revoked,
  ADD COLUMN IF NOT EXISTS biometric_access_removed TINYINT(1) NOT NULL DEFAULT 0 AFTER sessions_invalidated,
  ADD COLUMN IF NOT EXISTS it_processed_by INT NULL AFTER biometric_access_removed,
  ADD COLUMN IF NOT EXISTS it_processed_at DATETIME NULL AFTER it_processed_by,
  ADD COLUMN IF NOT EXISTS processed_by INT NULL AFTER it_processed_at;
